---
title: "CHES 16S Analysis"
author: "Theodora Karagounis"
date: "2024-07-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries

```{r libraries}
library(tidyverse)
library(qiime2R)
library(phyloseq)
library(readxl)
library(writexl)
library(vegan)
library(ggsignif)
library(ggpmisc)
library(ggtext)
```

# Define Directories

```{r define directories}

outpath <- 'Output/'
```

# Import Data

```{r data import}

physeq_noS<-qza_to_phyloseq(
    features = 'MergedRuns/sample-taxa-filtered-table_NYUCHES_R1R2merged.qza',
    tree= 'MergedRuns/rooted-tree_NYUCHES_R1R2merged.qza',
    taxonomy= 'MergedRuns/taxonomy-sample-taxa-filtered_NYUCHES_R1R2merged.qza',
    metadata ='NYU_CHES_Sample_Metadata.tsv')

physeq_noS
```

# Data Clean Up and Subsetting

```{r data clean up}

#Prune samples for any ASVs that are zero in all samples (there are none)
physeq_noS <- prune_taxa(taxa_sums(physeq_noS) > 0, physeq_noS)

#Defining NA labels
taxtable_noS <- data.frame(tax_table(physeq_noS))
taxtable_noS <- taxtable_noS %>%
  dplyr::mutate(Order = ifelse(is.na(Order), paste0(Class, "_unspecified"), Order)) %>%
  dplyr::mutate(Family = ifelse(is.na(Family), paste0(Order, "_unspecified"), Family)) %>%
  dplyr::mutate(Genus = ifelse(is.na(Genus), paste0(Family, "_unspecified"), Genus)) %>%
  dplyr::mutate(Species = ifelse(is.na(Species), paste0(Genus, "_unspecified"), Species))

phyloseq::tax_table(physeq_noS) <- as.matrix(taxtable_noS)

#Add info on timepoint
sample_info <- data.frame(sample_data(physeq_noS))
sample_info <- sample_info %>%
  dplyr::mutate(sample_id = row.names(.)) %>%
  dplyr::group_by(subject_id)%>%
  dplyr::mutate(timepoint = ifelse(age_weeks == min(age_weeks), 1, 2))%>%
  dplyr::ungroup()

sample_info <- sample_info %>%
  column_to_rownames(var = "sample_id")%>%
  dplyr::mutate(sample_id = row.names(.))

sample_order <- sample_names(physeq_noS)
  
sample_info <- sample_info[sample_order,]

sample_data(physeq_noS) <- sample_info

#Calculate relative abundance
physeq_noS.ASV.rel <- transform_sample_counts(physeq_noS, function(x) x/sum(x))

#Glom on genus level
physeq_noS.genus <- tax_glom(physeq_noS, "Genus")
physeq_noS.genus.rel <- transform_sample_counts(physeq_noS.genus, function(x) x/sum(x))

#Subsetting first timepoints
subjects_data<- data.frame(sample_data(physeq_noS)) %>%
arrange(subject_id, age_month)
first_timepoints <- subjects_data %>% group_by(subject_id) %>% dplyr::slice(1)
first_timepoints_list <- first_timepoints$sample_id

physeq_noS.ASV.timept1 <- physeq_noS %>%
  subset_samples(sample_id %in% first_timepoints_list)
physeq_noS.genus.timept1 <- physeq_noS.genus %>%
  subset_samples(sample_id %in% first_timepoints_list)

#AD samples only
physeq_noS.ASV.AD <- subset_samples(physeq_noS, case == "case")
physeq_noS.genus.AD <- subset_samples(physeq_noS.genus, case == "case")
```

# Alpha Diversity

## ASV

```{r alpha div ASV}

adiv_timept1 <- data.frame(
  "Observed" = phyloseq::estimate_richness(physeq_noS.ASV.timept1, measures = "Observed"),
  "Shannon" = phyloseq::estimate_richness(physeq_noS.ASV.timept1, measures = "Shannon"),
  "Simpson" = phyloseq::estimate_richness(physeq_noS.ASV.timept1, measures = "Simpson"),
  "InvSimpson" = phyloseq::estimate_richness(physeq_noS.ASV.timept1, measures = "InvSimpson")[, 1],
  "Status" = phyloseq::sample_data(physeq_noS.ASV.timept1)$case,
  "Saureus" = phyloseq::sample_data(physeq_noS.ASV.timept1)$Copies_per_100mgstool_lessthan1zerod_logtransformed,
  "Saureusyesno" = phyloseq::sample_data(physeq_noS.ASV.timept1)$Saureus_yes_no_lessthan1zerod,
  "age_week" = phyloseq::sample_data(physeq_noS.ASV.timept1)$age_weeks,
  "age_month"= phyloseq::sample_data(physeq_noS.ASV.timept1)$age_month,
  "subject" = phyloseq::sample_data(physeq_noS.ASV.timept1)$subject_id)

write_xlsx(adiv_timept1,paste0(outpath,"CHESadiv.xlsx"))

# Inverse Simpson
adiv_timept1 %>%
  ggplot(aes(x = paste(Status, Saureusyesno), y = InvSimpson, shape = Saureusyesno)) +
  geom_boxplot(outlier.color = NA) +
  scale_color_manual(values=c("#eb1543","#140dde"), labels = c("Atopic Dermatitis (AD)", "Healthy Control (HC)"))+
  scale_shape_manual(values = c(19, 19), labels = c("- Negative", "+ Positive")) +
  geom_jitter(aes(color = Status), height = 0, width = .2, size = 1) +
  labs(x = bquote(italic("S. aureus") ~"stool detection"), y = "Inverse Simpson Index", shape = bquote(italic("S. aureus") ~ "stool detection")) +
  scale_x_discrete(labels=c("-", "+", "-", "+")) +
  theme_minimal()+
  theme(axis.title = element_text(size = 12),
    axis.line.x = element_line(colour = "black", linewidth = 0.5),
    axis.line.y = element_line(colour = "black", linewidth = 0.5),
    axis.text.y = element_text(size = 11, color = "black"),
    axis.text.x = element_text(size = 18, color = "black"),
    strip.text = element_text(size = 14))+
  guides(colour = guide_legend(override.aes = list(size=3)))

ggsave(paste0(outpath,"Alpha Diversity/InverseSimpson1stTimepointASV.svg"), width = 5, height = 4)

kruskal.test(adiv_timept1[["InvSimpson"]] ~ interaction(adiv_timept1$Status,adiv_timept1$Saureusyesno))

#Focusing on AD 1st timepoints only
# Inverse Simpson Plot
adiv_timept1 %>%
  filter(Status == "case")%>%
  ggplot(aes(x = Saureusyesno, y = InvSimpson))+
  geom_boxplot(outlier.color = NA, aes(color = Saureusyesno)) +
  geom_jitter(height = 0, width = .2, size = 1, aes(color = Saureusyesno)) +
  scale_x_discrete(labels=c("-", "+")) +
  labs(x = bquote(italic("S. aureus") ~ ("stool detection")), y = "Inverse Simpson Index") + 
  geom_signif(comparisons = list(c("1", "0")), textsize = 4) +
  scale_color_manual(values=c("#606060","red"))+
  theme_minimal()+
  ylim(0,45)+
  theme(
    axis.line.x = element_line(colour = "black", linewidth = 0.5),
    axis.line.y = element_line(colour = "black", linewidth = 0.5),
    axis.title = element_text(size = 14),
    axis.text.y = element_text(size = 11, color = "black"),
    axis.text.x = element_text(size = 18, color = "black"),
    strip.text = element_text(size = 14),
    legend.position = "none")

ggsave(paste0(outpath,"Alpha Diversity/InverseSimpson_timept1_AD.svg"), width = 3, height = 4)
```

### Age

```{r adiv by age}

adiv <- data.frame(
  "InvSimpson" = phyloseq::estimate_richness(physeq_noS, measures = "InvSimpson")[, 1],
  "Status" = phyloseq::sample_data(physeq_noS)$case,
  "Saureus" = phyloseq::sample_data(physeq_noS)$Copies_per_100mgstool_lessthan1zerod_logtransformed,
  "Saureusyesno" = phyloseq::sample_data(physeq_noS)$Saureus_yes_no_lessthan1zerod,
  "age_week" = phyloseq::sample_data(physeq_noS)$age_weeks,
  "age_month"= phyloseq::sample_data(physeq_noS)$age_month,
  "subject" = phyloseq::sample_data(physeq_noS)$subject_id)

adiv %>%
  ggplot(aes(x = age_month, y = InvSimpson))+
  geom_point()+
  geom_smooth(method = "lm")+
  labs(x = "Age (month)", y = "Diversity Metric")+
  ggtitle("Inverse Simpson")+
  stat_poly_eq(
    aes(label = paste(..eq.label.., ..adj.rr.label.., ..p.value.label.., sep = "~~~")),
    formula = y ~ x, 
    parse = TRUE, 
    vstep = 0.08,
    size = 4
  ) +
 theme(axis.title = element_text(size = 12),
    axis.line.x = element_line(colour = "black", linewidth = 0.5),
    axis.line.y = element_line(colour = "black", linewidth = 0.5),
    axis.text.y = element_text(size = 11, color = "black"),
    axis.text.x = element_text(size = 11, color = "black"))

ggsave(paste0(outpath,"Alpha Diversity/InvSimpsonbyAge.svg"))
```

# Beta Diversity

## Genus

```{r Bray Curtis plotting for all genus}

#Bray Curtis
ord_BrayCurtis_PCoA_genus <- phyloseq::ordinate(physeq_noS.genus.rel, "PCoA", "bray")
p_genus <-phyloseq::plot_ordination(physeq_noS.genus.rel, ord_BrayCurtis_PCoA_genus , type="samples") 
breaks <- c(min(sample_data(physeq_noS.genus.rel)$age_month), 5,10, max(sample_data(physeq_noS.genus.rel)$age_month))
labels <- round(breaks, 1)
```

### Age

#### 1st Timepoints

```{r Bray Curtis genus 1st timepoints}

#Make everything relative
physeq_rel = transform_sample_counts(physeq_noS.genus.timept1, function(x) x/sum(x))

#Testing significance
BrayCurtis<- distance(physeq_rel, method = "bray")
sig <- adonis2(BrayCurtis ~ phyloseq::sample_data(physeq_rel)$age_month)
p_value <- sig[1,5]
R_value <-round(sig[1,3], digits = 3)

#Plot above
p2 <- p_genus

p2$data <- p2$data%>%
  filter(timepoint ==1)

p_save <- p2 +geom_point(data = p2$data, size = 2, aes(color = age_month)) +
  labs(title = "Bray-Curtis dissimilarity") +
  scale_color_viridis_c(name = "Age (months)",
                        direction=-1,
                        breaks = breaks,
                        labels = labels)+
  theme(axis.title = element_text(size = 12),
    axis.line.x = element_line(colour = "black", linewidth = 0.5),
    axis.line.y = element_line(colour = "black", linewidth = 0.5),
    axis.text.y = element_text(size = 11, color = "black"),
    axis.text.x = element_text(size = 11, color = "black"))+
  coord_fixed(xlim = c(-0.65,0.6),ylim = c(-0.55,0.5), clip = "off") +
  annotate("text", x = 0.45, y = 0.61, label = paste0("PERMANOVA: R^2 = ",R_value,", p = ",p_value))

p_save

ggsave(filename = paste0(outpath,"Beta Diversity/BrayCurtis_genus_Age_1stTimepts.svg"), plot = egg::set_panel_size(p=p_save, width=unit(10, "cm"), height=unit(9, "cm")))
```

### AD vs. HC

#### 1st Timepoints

```{r Bray Curtis genus 1st timepoints AD vs. HC}

#Make everything relative
physeq_rel = transform_sample_counts(physeq_noS.genus.timept1, function(x) x/sum(x))

#Testing significance
BrayCurtis<- distance(physeq_rel, method = "bray")
sig <- adonis2(BrayCurtis ~ phyloseq::sample_data(physeq_rel)$case)
p_value <- sig[1,5]
R_value <-round(sig[1,3], digits = 3)

#Plot above looking AD vs. HC
p2 <- p_genus

p2$data <- p2$data %>%
  filter(timepoint == 1)

p_save <- p2 + geom_point(size = 2, aes(color = sample_data(physeq_rel)$case)) +
  labs(title = "Bray-Curtis dissimilarity") +
  scale_color_manual(name = "Disease Status", values = c("#FE3409", "#0745F7"), labels = c("Atopic Dermatitis", "Healthy Control")) +
  scale_fill_manual(name = "Disease Status", values = c("#FE3409", "#0745F7"), labels = c("Atopic Dermatitis", "Healthy Control")) +
  stat_ellipse(aes(color=sample_data(physeq_rel)$case, fill=sample_data(physeq_rel)$case),
               geom = "polygon",
               alpha=.3,
               linewidth=.20, level=.9, type="t") +
  theme_minimal()+
  theme(axis.title = element_text(size = 12),
    axis.line.x = element_line(colour = "black", linewidth = 0.5),
    axis.line.y = element_line(colour = "black", linewidth = 0.5),
    axis.text.y = element_text(size = 11, color = "black"),
    axis.text.x = element_text(size = 11, color = "black"),
    legend.justification = "top",
    rect = element_rect(fill = "transparent"))+
  coord_fixed(xlim = c(-0.65,0.6),ylim = c(-0.55,0.5), clip = "off") +
  annotate("text", x = 0.45, y = 0.61, label = paste0("PERMANOVA: R^2 = ",R_value,", p = ",p_value))

p_save

ggsave(filename = paste0(outpath,"Beta Diversity/BrayCurtis_genus_ADvHC_1stTimept.svg"), plot = egg::set_panel_size(p=p_save, width=unit(10, "cm"), height=unit(9, "cm")))
```

### S. aureus yes vs. no

#### 1st Timepoint

```{r Bray Curtis genus 1st timepoints S. aureus yes no}

#Make everything relative
physeq_rel = transform_sample_counts(physeq_noS.genus.timept1, function(x) x/sum(x))

#Testing significance
BrayCurtis<- distance(physeq_rel, method = "bray")
sig <- adonis2(BrayCurtis ~ phyloseq::sample_data(physeq_rel)$Saureus_yes_no_lessthan1zerod)
p_value <- sig[1,5]
R_value <-round(sig[1,3], digits = 3)

#Plot above looking at S. aureus
p2 <- p_genus

p2$data <- p2$data %>%
  filter(timepoint == 1)

p_save <- p2 + geom_point(data = p2$data, size = 2, aes(color = Saureus_yes_no_lessthan1zerod)) +
  labs(title = "Bray-Curtis dissimilarity") +
  scale_color_manual(name = bquote(italic("S. aureus") ~ "stool detection"), values = c("darkgrey","darkred"), labels = c("Negative", "Positive")) +
      scale_fill_manual(name = bquote(italic("S. aureus") ~ "stool detection"), values = c("darkgrey","darkred"), labels = c("Negative", "Positive")) +
  stat_ellipse(data = p2$data, aes(color=Saureus_yes_no_lessthan1zerod, fill=Saureus_yes_no_lessthan1zerod),
               geom = "polygon",
               alpha=.3,
               linewidth=.20, level=.9, type="t") +
  theme_minimal() +
  theme(axis.title = element_text(size = 12),
    axis.line.x = element_line(colour = "black", linewidth = 0.5),
    axis.line.y = element_line(colour = "black", linewidth = 0.5),
    axis.text.y = element_text(size = 11, color = "black"),
    axis.text.x = element_text(size = 11, color = "black"))+
  coord_fixed(xlim = c(-0.65,0.6),ylim = c(-0.55,0.5), clip = "off") +
  annotate("text", x = 0.45, y = 0.61, label = paste0("PERMANOVA: R^2 = ",R_value,", p = ",p_value))
  
p_save

ggsave(filename = paste0(outpath,"Beta Diversity/BrayCurtis_genus_SaureusR_1stTimept.svg"), plot = egg::set_panel_size(p=p_save, width=unit(10, "cm"), height=unit(9, "cm")))
```
